codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "0...100"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true

status:
  project:
    default:
      target: auto
      threshold: 1%
      if_not_found: success
  patch:
    default:
      target: auto
      threshold: 1%
      if_not_found: success

ignore:
  - "test/**"
  - "example/**"
  - "tool/**"
