/*
 * Copyright (C) 2026, Isaque Neves <insinfo2008@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import 'dart:typed_data';

import 'pdf_content_lexer.dart';
import 'pdf_content_operator.dart';

/// Converts the bytes of a content stream into a list of operators.
///
/// The design follows the same principle as MuPDF's `pdf_processor`: a single
/// loop pushes operands and, on reaching a keyword, hands out the operator
/// with the accumulated stack. The difference is that here the result is a
/// list of data — not a set of callbacks — because the immediate goal is to
/// reserialize and analyze, not to render.
///
/// The parser never throws on malformed content: leftover operands are
/// discarded at the end, unknown operators are preserved as they are, and
/// unexpected bytes become keywords. A content stream is often generated by
/// tools with small defects, and aborting the whole read would be worse than
/// carrying on.
class PdfContentParser {
  /// Creates a parser over [data].
  PdfContentParser(
    this.data, {
    this.keepComments = false,
    this.maxOperands = 512,
  });

  /// Content stream bytes, already decompressed.
  final Uint8List data;

  /// When `true`, comments become [PdfContentComment] in the output.
  final bool keepComments;

  /// Limit of operands accumulated before an operator; keeps memory use
  /// bounded on corrupted streams.
  final int maxOperands;

  /// Shortcut: tokenizes [data] and returns the operators.
  static List<PdfContentOperator> parseBytes(
    Uint8List data, {
    bool keepComments = false,
  }) =>
      PdfContentParser(data, keepComments: keepComments).parse();

  /// Tokenizes the whole stream.
  List<PdfContentOperator> parse() {
    final lexer = PdfContentLexer(data);
    final operators = <PdfContentOperator>[];
    var operands = <PdfContentValue>[];

    while (true) {
      final token = lexer.next();
      if (token.kind == PdfContentTokenKind.endOfData) break;

      switch (token.kind) {
        case PdfContentTokenKind.comment:
          if (keepComments) operators.add(PdfContentComment(token.text));
          break;

        case PdfContentTokenKind.keyword:
          final word = token.text;
          if (word == 'true') {
            _push(operands, const PdfContentBool(true));
            break;
          }
          if (word == 'false') {
            _push(operands, const PdfContentBool(false));
            break;
          }
          if (word == 'null') {
            _push(operands, const PdfContentNull());
            break;
          }
          if (word == 'BI') {
            final image = _readInlineImage(lexer);
            if (image != null) operators.add(image);
            operands = <PdfContentValue>[];
            break;
          }
          if (word == '{' || word == '}') {
            // PostScript function delimiters do not occur in content
            // streams; if they show up they are preserved as a bare
            // operator.
            operators.add(PdfContentOperator(word));
            operands = <PdfContentValue>[];
            break;
          }
          operators.add(PdfContentOperator(word, operands));
          operands = <PdfContentValue>[];
          break;

        default:
          final value = _valueOf(token, lexer);
          if (value != null) _push(operands, value);
      }
    }

    // Operands with no operator at the end of the stream are discarded:
    // there is no operation for them to belong to.
    return operators;
  }

  void _push(List<PdfContentValue> operands, PdfContentValue value) {
    if (operands.length >= maxOperands) {
      operands.removeAt(0);
    }
    operands.add(value);
  }

  /// Converts a simple token into a value, reading arrays and dictionaries
  /// recursively. Returns `null` for stray closing tokens.
  PdfContentValue? _valueOf(PdfContentToken token, PdfContentLexer lexer) {
    switch (token.kind) {
      case PdfContentTokenKind.number:
        return PdfContentNumber(
            PdfContentLexer.parseNumber(token.text), token.text);

      case PdfContentTokenKind.name:
        return PdfContentName(
            token.text, String.fromCharCodes(data, token.start, token.end));

      case PdfContentTokenKind.literalString:
        return PdfContentString(token.bytes ?? Uint8List(0),
            raw: data.sublist(token.start, token.end));

      case PdfContentTokenKind.hexString:
        return PdfContentString(token.bytes ?? Uint8List(0),
            hex: true, raw: data.sublist(token.start, token.end));

      case PdfContentTokenKind.arrayStart:
        return _readArray(lexer);

      case PdfContentTokenKind.dictStart:
        return _readDict(lexer);

      case PdfContentTokenKind.arrayEnd:
      case PdfContentTokenKind.dictEnd:
      case PdfContentTokenKind.comment:
      case PdfContentTokenKind.keyword:
      case PdfContentTokenKind.endOfData:
        return null;
    }
  }

  PdfContentArray _readArray(PdfContentLexer lexer, [int depth = 0]) {
    final values = <PdfContentValue>[];
    if (depth > 32) return PdfContentArray(values);

    while (true) {
      final token = lexer.next();
      if (token.kind == PdfContentTokenKind.arrayEnd ||
          token.kind == PdfContentTokenKind.endOfData) {
        break;
      }
      if (token.kind == PdfContentTokenKind.dictEnd) break; // unbalanced
      if (token.kind == PdfContentTokenKind.comment) continue;
      if (token.kind == PdfContentTokenKind.keyword) {
        // `true`/`false`/`null` inside an array; any other word is garbage
        // and becomes null so the array does not get misaligned.
        if (token.text == 'true') {
          values.add(const PdfContentBool(true));
        } else if (token.text == 'false') {
          values.add(const PdfContentBool(false));
        } else if (token.text == 'null') {
          values.add(const PdfContentNull());
        }
        continue;
      }
      if (token.kind == PdfContentTokenKind.arrayStart) {
        values.add(_readArray(lexer, depth + 1));
        continue;
      }
      if (token.kind == PdfContentTokenKind.dictStart) {
        values.add(_readDict(lexer, depth + 1));
        continue;
      }
      final value = _valueOf(token, lexer);
      if (value != null) values.add(value);
    }
    return PdfContentArray(values);
  }

  PdfContentDict _readDict(PdfContentLexer lexer, [int depth = 0]) {
    final values = <String, PdfContentValue>{};
    if (depth > 32) return PdfContentDict(values);

    while (true) {
      final keyToken = lexer.next();
      if (keyToken.kind == PdfContentTokenKind.dictEnd ||
          keyToken.kind == PdfContentTokenKind.endOfData) {
        break;
      }
      if (keyToken.kind == PdfContentTokenKind.comment) continue;
      if (keyToken.kind != PdfContentTokenKind.name) {
        // Invalid key: skip the token and keep trying.
        continue;
      }

      final valueToken = lexer.next();
      if (valueToken.kind == PdfContentTokenKind.dictEnd ||
          valueToken.kind == PdfContentTokenKind.endOfData) {
        break;
      }
      final value = valueToken.kind == PdfContentTokenKind.arrayStart
          ? _readArray(lexer, depth + 1)
          : valueToken.kind == PdfContentTokenKind.dictStart
              ? _readDict(lexer, depth + 1)
              : valueToken.kind == PdfContentTokenKind.keyword
                  ? _keywordValue(valueToken.text)
                  : _valueOf(valueToken, lexer);
      if (value != null) values[keyToken.text] = value;
    }
    return PdfContentDict(values);
  }

  PdfContentValue? _keywordValue(String word) {
    if (word == 'true') return const PdfContentBool(true);
    if (word == 'false') return const PdfContentBool(false);
    if (word == 'null') return const PdfContentNull();
    return null;
  }

  // ---------------------------------------------------------------------------
  // Inline image
  // ---------------------------------------------------------------------------

  /// Reads `BI <keys> ID <bytes> EI` starting just past the `BI`.
  ///
  /// This is the treacherous part of the format: the bytes after the `ID` are
  /// binary and may contain any sequence, `EI` included. The order of the
  /// strategies is:
  ///
  /// 1. `/L` (or `/Length`) declared: use the length and check that `EI`
  ///    really does come next;
  /// 2. image without a filter: compute the exact size from `/W`, `/H`, `/BPC`
  ///    and the number of components of `/CS`, and check the `EI`;
  /// 3. general case: look for an `EI` preceded by whitespace and followed by
  ///    whitespace, a delimiter or the end of the data.
  PdfInlineImage? _readInlineImage(PdfContentLexer lexer) {
    final values = <String, PdfContentValue>{};

    // Key/value pairs up to the `ID`.
    var sawId = false;
    while (!sawId) {
      final keyToken = lexer.next();
      if (keyToken.kind == PdfContentTokenKind.endOfData) break;
      if (keyToken.kind == PdfContentTokenKind.comment) continue;
      if (keyToken.kind == PdfContentTokenKind.keyword) {
        if (keyToken.text == 'ID') {
          sawId = true;
          break;
        }
        if (keyToken.text == 'EI') {
          // `BI … EI` with no data: empty image.
          return PdfInlineImage(
              PdfContentDict(values), Uint8List(0),
              separator: const <int>[]);
        }
        continue;
      }
      if (keyToken.kind != PdfContentTokenKind.name) continue;

      final valueToken = lexer.next();
      if (valueToken.kind == PdfContentTokenKind.endOfData) break;
      if (valueToken.kind == PdfContentTokenKind.keyword &&
          valueToken.text == 'ID') {
        sawId = true;
        break;
      }
      final value = valueToken.kind == PdfContentTokenKind.arrayStart
          ? _readArray(lexer)
          : valueToken.kind == PdfContentTokenKind.dictStart
              ? _readDict(lexer)
              : valueToken.kind == PdfContentTokenKind.keyword
                  ? _keywordValue(valueToken.text)
                  : _valueOf(valueToken, lexer);
      if (value != null) values[keyToken.text] = value;
    }

    if (!sawId) return null;

    final dict = PdfContentDict(values);

    // A single whitespace byte separates `ID` from the data; CRLF counts as
    // one.
    final separator = <int>[];
    if (lexer.position < data.length &&
        PdfContentLexer.isWhitespace(data[lexer.position])) {
      separator.add(data[lexer.position]);
      lexer.position++;
      if (separator.first == 0x0D &&
          lexer.position < data.length &&
          data[lexer.position] == 0x0A) {
        separator.add(0x0A);
        lexer.position++;
      }
    }

    final dataStart = lexer.position;
    var dataEnd = -1;
    var declared = false;

    final declaredLength = _intOf(dict.lookup('/L', '/Length'));
    if (declaredLength != null &&
        declaredLength >= 0 &&
        dataStart + declaredLength <= data.length &&
        _eiFollows(dataStart + declaredLength)) {
      dataEnd = dataStart + declaredLength;
      declared = true;
    }

    if (dataEnd < 0 && !_hasFilter(dict)) {
      final computed = _uncompressedLength(dict);
      if (computed != null &&
          computed >= 0 &&
          dataStart + computed <= data.length &&
          _eiFollows(dataStart + computed)) {
        dataEnd = dataStart + computed;
      }
    }

    if (dataEnd < 0) {
      dataEnd = _scanForEi(dataStart);
    }

    final bytes = data.sublist(dataStart, dataEnd);

    // Consume the `EI` and leave the lexer right after it.
    lexer.position = dataEnd;
    final probe = PdfContentLexer(data, start: dataEnd);
    final token = probe.next();
    if (token.kind == PdfContentTokenKind.keyword && token.text == 'EI') {
      lexer.position = probe.position;
    }

    return PdfInlineImage(dict, bytes,
        separator: separator, lengthWasDeclared: declared);
  }

  bool _hasFilter(PdfContentDict dict) {
    final filter = dict.lookup('/Filter', '/F');
    if (filter == null) return false;
    if (filter is PdfContentArray) return filter.values.isNotEmpty;
    return filter is PdfContentName;
  }

  /// Exact data size of an inline image without a filter.
  int? _uncompressedLength(PdfContentDict dict) {
    final width = _intOf(dict.lookup('/Width', '/W'));
    final height = _intOf(dict.lookup('/Height', '/H'));
    if (width == null || height == null || width <= 0 || height <= 0) {
      return null;
    }

    final mask = dict.lookup('/ImageMask', '/IM');
    final isMask = mask is PdfContentBool && mask.value;
    var bits = _intOf(dict.lookup('/BitsPerComponent', '/BPC')) ?? (isMask ? 1 : 8);
    if (isMask) bits = 1;

    final components = isMask ? 1 : _componentsOf(dict);
    if (components == null) return null;

    final rowBits = width * bits * components;
    final rowBytes = (rowBits + 7) ~/ 8;
    return rowBytes * height;
  }

  int? _componentsOf(PdfContentDict dict) {
    final space = dict.lookup('/ColorSpace', '/CS');
    if (space == null) return 1;
    if (space is PdfContentArray) {
      // `[/I /RGB 255 <…>]` — indexed, one component per sample.
      final first = space.values.isEmpty ? null : space.values.first;
      if (first is PdfContentName &&
          (first.value == '/I' || first.value == '/Indexed')) {
        return 1;
      }
      return null; // color space named in the resources: not computable here
    }
    if (space is! PdfContentName) return null;
    switch (space.value) {
      case '/G':
      case '/DeviceGray':
      case '/CalGray':
        return 1;
      case '/RGB':
      case '/DeviceRGB':
      case '/CalRGB':
        return 3;
      case '/CMYK':
      case '/DeviceCMYK':
        return 4;
      case '/I':
      case '/Indexed':
        return 1;
      default:
        return null; // page resource name
    }
  }

  int? _intOf(PdfContentValue? value) =>
      value is PdfContentNumber ? value.asInt : null;

  /// Checks whether, starting at [position] and ignoring whitespace, an `EI`
  /// comes next followed by whitespace, a delimiter or the end of the data.
  bool _eiFollows(int position) {
    var i = position;
    while (i < data.length && PdfContentLexer.isWhitespace(data[i])) {
      i++;
    }
    if (i + 1 >= data.length) return false;
    if (data[i] != 0x45 || data[i + 1] != 0x49) return false; // E I
    final after = i + 2;
    if (after >= data.length) return true;
    return PdfContentLexer.isTokenBoundary(data[after]);
  }

  /// Looks for the `EI` that closes the image, returning the end of the data.
  ///
  /// Accepts only an `EI` preceded by whitespace and followed by whitespace, a
  /// delimiter or the end of the data — the same heuristic MuPDF uses. Without
  /// `/L` this is the best that can be done: the image bytes may contain the
  /// `EI` sequence by chance.
  int _scanForEi(int dataStart) {
    for (var i = dataStart; i + 1 < data.length; i++) {
      if (data[i] != 0x45 || data[i + 1] != 0x49) continue; // E I
      if (i <= dataStart) continue;
      if (!PdfContentLexer.isWhitespace(data[i - 1])) continue;
      final after = i + 2;
      if (after < data.length && !PdfContentLexer.isTokenBoundary(data[after])) {
        continue;
      }
      // The whitespace before the `EI` is part of the delimiter, not of the
      // data.
      return i - 1;
    }
    return data.length;
  }
}
